#if defined(VK_VERSION_1_0)
VOLKGEN(vkAllocateCommandBuffers)
VOLKGEN(vkAllocateDescriptorSets)
VOLKGEN(vkAllocateMemory)
VOLKGEN(vkBeginCommandBuffer)
VOLKGEN(vkBindBufferMemory)
VOLKGEN(vkBindImageMemory)
VOLKGEN(vkCmdBeginQuery)
VOLKGEN(vkCmdBeginRenderPass)
VOLKGEN(vkCmdBindDescriptorSets)
VOLKGEN(vkCmdBindIndexBuffer)
VOLKGEN(vkCmdBindPipeline)
VOLKGEN(vkCmdBindVertexBuffers)
VOLKGEN(vkCmdBlitImage)
VOLKGEN(vkCmdClearAttachments)
VOLKGEN(vkCmdClearColorImage)
VOLKGEN(vkCmdClearDepthStencilImage)
VOLKGEN(vkCmdCopyBuffer)
VOLKGEN(vkCmdCopyBufferToImage)
VOLKGEN(vkCmdCopyImage)
VOLKGEN(vkCmdCopyImageToBuffer)
VOLKGEN(vkCmdCopyQueryPoolResults)
VOLKGEN(vkCmdDispatch)
VOLKGEN(vkCmdDispatchIndirect)
VOLKGEN(vkCmdDraw)
VOLKGEN(vkCmdDrawIndexed)
VOLKGEN(vkCmdDrawIndexedIndirect)
VOLKGEN(vkCmdDrawIndirect)
VOLKGEN(vkCmdEndQuery)
VOLKGEN(vkCmdEndRenderPass)
VOLKGEN(vkCmdExecuteCommands)
VOLKGEN(vkCmdFillBuffer)
VOLKGEN(vkCmdNextSubpass)
VOLKGEN(vkCmdPipelineBarrier)
VOLKGEN(vkCmdPushConstants)
VOLKGEN(vkCmdResetEvent)
VOLKGEN(vkCmdResetQueryPool)
VOLKGEN(vkCmdResolveImage)
VOLKGEN(vkCmdSetBlendConstants)
VOLKGEN(vkCmdSetDepthBias)
VOLKGEN(vkCmdSetDepthBounds)
VOLKGEN(vkCmdSetEvent)
VOLKGEN(vkCmdSetLineWidth)
VOLKGEN(vkCmdSetScissor)
VOLKGEN(vkCmdSetStencilCompareMask)
VOLKGEN(vkCmdSetStencilReference)
VOLKGEN(vkCmdSetStencilWriteMask)
VOLKGEN(vkCmdSetViewport)
VOLKGEN(vkCmdUpdateBuffer)
VOLKGEN(vkCmdWaitEvents)
VOLKGEN(vkCmdWriteTimestamp)
VOLKGEN(vkCreateBuffer)
VOLKGEN(vkCreateBufferView)
VOLKGEN(vkCreateCommandPool)
VOLKGEN(vkCreateComputePipelines)
VOLKGEN(vkCreateDescriptorPool)
VOLKGEN(vkCreateDescriptorSetLayout)
VOLKGEN(vkCreateEvent)
VOLKGEN(vkCreateFence)
VOLKGEN(vkCreateFramebuffer)
VOLKGEN(vkCreateGraphicsPipelines)
VOLKGEN(vkCreateImage)
VOLKGEN(vkCreateImageView)
VOLKGEN(vkCreatePipelineCache)
VOLKGEN(vkCreatePipelineLayout)
VOLKGEN(vkCreateQueryPool)
VOLKGEN(vkCreateRenderPass)
VOLKGEN(vkCreateSampler)
VOLKGEN(vkCreateSemaphore)
VOLKGEN(vkCreateShaderModule)
VOLKGEN(vkDestroyBuffer)
VOLKGEN(vkDestroyBufferView)
VOLKGEN(vkDestroyCommandPool)
VOLKGEN(vkDestroyDescriptorPool)
VOLKGEN(vkDestroyDescriptorSetLayout)
VOLKGEN(vkDestroyDevice)
VOLKGEN(vkDestroyEvent)
VOLKGEN(vkDestroyFence)
VOLKGEN(vkDestroyFramebuffer)
VOLKGEN(vkDestroyImage)
VOLKGEN(vkDestroyImageView)
VOLKGEN(vkDestroyPipeline)
VOLKGEN(vkDestroyPipelineCache)
VOLKGEN(vkDestroyPipelineLayout)
VOLKGEN(vkDestroyQueryPool)
VOLKGEN(vkDestroyRenderPass)
VOLKGEN(vkDestroySampler)
VOLKGEN(vkDestroySemaphore)
VOLKGEN(vkDestroyShaderModule)
VOLKGEN(vkDeviceWaitIdle)
VOLKGEN(vkEndCommandBuffer)
VOLKGEN(vkFlushMappedMemoryRanges)
VOLKGEN(vkFreeCommandBuffers)
VOLKGEN(vkFreeDescriptorSets)
VOLKGEN(vkFreeMemory)
VOLKGEN(vkGetBufferMemoryRequirements)
VOLKGEN(vkGetDeviceMemoryCommitment)
VOLKGEN(vkGetDeviceQueue)
VOLKGEN(vkGetEventStatus)
VOLKGEN(vkGetFenceStatus)
VOLKGEN(vkGetImageMemoryRequirements)
VOLKGEN(vkGetImageSparseMemoryRequirements)
VOLKGEN(vkGetImageSubresourceLayout)
VOLKGEN(vkGetPipelineCacheData)
VOLKGEN(vkGetQueryPoolResults)
VOLKGEN(vkGetRenderAreaGranularity)
VOLKGEN(vkInvalidateMappedMemoryRanges)
VOLKGEN(vkMapMemory)
VOLKGEN(vkMergePipelineCaches)
VOLKGEN(vkQueueBindSparse)
VOLKGEN(vkQueueSubmit)
VOLKGEN(vkQueueWaitIdle)
VOLKGEN(vkResetCommandBuffer)
VOLKGEN(vkResetCommandPool)
VOLKGEN(vkResetDescriptorPool)
VOLKGEN(vkResetEvent)
VOLKGEN(vkResetFences)
VOLKGEN(vkSetEvent)
VOLKGEN(vkUnmapMemory)
VOLKGEN(vkUpdateDescriptorSets)
VOLKGEN(vkWaitForFences)
#endif /* defined(VK_VERSION_1_0) */
#if defined(VK_VERSION_1_1)
VOLKGEN(vkBindBufferMemory2)
VOLKGEN(vkBindImageMemory2)
VOLKGEN(vkCmdDispatchBase)
VOLKGEN(vkCmdSetDeviceMask)
VOLKGEN(vkCreateDescriptorUpdateTemplate)
VOLKGEN(vkCreateSamplerYcbcrConversion)
VOLKGEN(vkDestroyDescriptorUpdateTemplate)
VOLKGEN(vkDestroySamplerYcbcrConversion)
VOLKGEN(vkGetBufferMemoryRequirements2)
VOLKGEN(vkGetDescriptorSetLayoutSupport)
VOLKGEN(vkGetDeviceGroupPeerMemoryFeatures)
VOLKGEN(vkGetDeviceQueue2)
VOLKGEN(vkGetImageMemoryRequirements2)
VOLKGEN(vkGetImageSparseMemoryRequirements2)
VOLKGEN(vkTrimCommandPool)
VOLKGEN(vkUpdateDescriptorSetWithTemplate)
#endif /* defined(VK_VERSION_1_1) */
#if defined(VK_AMD_buffer_marker)
VOLKGEN(vkCmdWriteBufferMarkerAMD)
#endif /* defined(VK_AMD_buffer_marker) */
#if defined(VK_AMD_draw_indirect_count)
VOLKGEN(vkCmdDrawIndexedIndirectCountAMD)
VOLKGEN(vkCmdDrawIndirectCountAMD)
#endif /* defined(VK_AMD_draw_indirect_count) */
#if defined(VK_AMD_shader_info)
VOLKGEN(vkGetShaderInfoAMD)
#endif /* defined(VK_AMD_shader_info) */
#if defined(VK_ANDROID_external_memory_android_hardware_buffer)
VOLKGEN(vkGetAndroidHardwareBufferPropertiesANDROID)
VOLKGEN(vkGetMemoryAndroidHardwareBufferANDROID)
#endif /* defined(VK_ANDROID_external_memory_android_hardware_buffer) */
#if defined(VK_ANDROID_native_buffer)
VOLKGEN(vkAcquireImageANDROID)
VOLKGEN(vkGetSwapchainGrallocUsageANDROID)
VOLKGEN(vkQueueSignalReleaseImageANDROID)
#endif /* defined(VK_ANDROID_native_buffer) */
#if defined(VK_EXT_debug_marker)
VOLKGEN(vkCmdDebugMarkerBeginEXT)
VOLKGEN(vkCmdDebugMarkerEndEXT)
VOLKGEN(vkCmdDebugMarkerInsertEXT)
VOLKGEN(vkDebugMarkerSetObjectNameEXT)
VOLKGEN(vkDebugMarkerSetObjectTagEXT)
#endif /* defined(VK_EXT_debug_marker) */
#if defined(VK_EXT_debug_utils)
VOLKGEN(vkCmdBeginDebugUtilsLabelEXT)
VOLKGEN(vkCmdEndDebugUtilsLabelEXT)
VOLKGEN(vkCmdInsertDebugUtilsLabelEXT)
VOLKGEN(vkQueueBeginDebugUtilsLabelEXT)
VOLKGEN(vkQueueEndDebugUtilsLabelEXT)
VOLKGEN(vkQueueInsertDebugUtilsLabelEXT)
VOLKGEN(vkSetDebugUtilsObjectNameEXT)
VOLKGEN(vkSetDebugUtilsObjectTagEXT)
#endif /* defined(VK_EXT_debug_utils) */
#if defined(VK_EXT_discard_rectangles)
VOLKGEN(vkCmdSetDiscardRectangleEXT)
#endif /* defined(VK_EXT_discard_rectangles) */
#if defined(VK_EXT_display_control)
VOLKGEN(vkDisplayPowerControlEXT)
VOLKGEN(vkGetSwapchainCounterEXT)
VOLKGEN(vkRegisterDeviceEventEXT)
VOLKGEN(vkRegisterDisplayEventEXT)
#endif /* defined(VK_EXT_display_control) */
#if defined(VK_EXT_external_memory_host)
VOLKGEN(vkGetMemoryHostPointerPropertiesEXT)
#endif /* defined(VK_EXT_external_memory_host) */
#if defined(VK_EXT_hdr_metadata)
VOLKGEN(vkSetHdrMetadataEXT)
#endif /* defined(VK_EXT_hdr_metadata) */
#if defined(VK_EXT_sample_locations)
VOLKGEN(vkCmdSetSampleLocationsEXT)
#endif /* defined(VK_EXT_sample_locations) */
#if defined(VK_EXT_validation_cache)
VOLKGEN(vkCreateValidationCacheEXT)
VOLKGEN(vkDestroyValidationCacheEXT)
VOLKGEN(vkGetValidationCacheDataEXT)
VOLKGEN(vkMergeValidationCachesEXT)
#endif /* defined(VK_EXT_validation_cache) */
#if defined(VK_GOOGLE_display_timing)
VOLKGEN(vkGetPastPresentationTimingGOOGLE)
VOLKGEN(vkGetRefreshCycleDurationGOOGLE)
#endif /* defined(VK_GOOGLE_display_timing) */
#if defined(VK_KHR_bind_memory2)
VOLKGEN(vkBindBufferMemory2KHR)
VOLKGEN(vkBindImageMemory2KHR)
#endif /* defined(VK_KHR_bind_memory2) */
#if defined(VK_KHR_descriptor_update_template)
VOLKGEN(vkCreateDescriptorUpdateTemplateKHR)
VOLKGEN(vkDestroyDescriptorUpdateTemplateKHR)
VOLKGEN(vkUpdateDescriptorSetWithTemplateKHR)
#endif /* defined(VK_KHR_descriptor_update_template) */
#if defined(VK_KHR_device_group)
VOLKGEN(vkCmdDispatchBaseKHR)
VOLKGEN(vkCmdSetDeviceMaskKHR)
VOLKGEN(vkGetDeviceGroupPeerMemoryFeaturesKHR)
#endif /* defined(VK_KHR_device_group) */
#if defined(VK_KHR_display_swapchain)
VOLKGEN(vkCreateSharedSwapchainsKHR)
#endif /* defined(VK_KHR_display_swapchain) */
#if defined(VK_KHR_external_fence_fd)
VOLKGEN(vkGetFenceFdKHR)
VOLKGEN(vkImportFenceFdKHR)
#endif /* defined(VK_KHR_external_fence_fd) */
#if defined(VK_KHR_external_fence_win32)
VOLKGEN(vkGetFenceWin32HandleKHR)
VOLKGEN(vkImportFenceWin32HandleKHR)
#endif /* defined(VK_KHR_external_fence_win32) */
#if defined(VK_KHR_external_memory_fd)
VOLKGEN(vkGetMemoryFdKHR)
VOLKGEN(vkGetMemoryFdPropertiesKHR)
#endif /* defined(VK_KHR_external_memory_fd) */
#if defined(VK_KHR_external_memory_win32)
VOLKGEN(vkGetMemoryWin32HandleKHR)
VOLKGEN(vkGetMemoryWin32HandlePropertiesKHR)
#endif /* defined(VK_KHR_external_memory_win32) */
#if defined(VK_KHR_external_semaphore_fd)
VOLKGEN(vkGetSemaphoreFdKHR)
VOLKGEN(vkImportSemaphoreFdKHR)
#endif /* defined(VK_KHR_external_semaphore_fd) */
#if defined(VK_KHR_external_semaphore_win32)
VOLKGEN(vkGetSemaphoreWin32HandleKHR)
VOLKGEN(vkImportSemaphoreWin32HandleKHR)
#endif /* defined(VK_KHR_external_semaphore_win32) */
#if defined(VK_KHR_get_memory_requirements2)
VOLKGEN(vkGetBufferMemoryRequirements2KHR)
VOLKGEN(vkGetImageMemoryRequirements2KHR)
VOLKGEN(vkGetImageSparseMemoryRequirements2KHR)
#endif /* defined(VK_KHR_get_memory_requirements2) */
#if defined(VK_KHR_maintenance1)
VOLKGEN(vkTrimCommandPoolKHR)
#endif /* defined(VK_KHR_maintenance1) */
#if defined(VK_KHR_maintenance3)
VOLKGEN(vkGetDescriptorSetLayoutSupportKHR)
#endif /* defined(VK_KHR_maintenance3) */
#if defined(VK_KHR_push_descriptor)
VOLKGEN(vkCmdPushDescriptorSetKHR)
#endif /* defined(VK_KHR_push_descriptor) */
#if defined(VK_KHR_sampler_ycbcr_conversion)
VOLKGEN(vkCreateSamplerYcbcrConversionKHR)
VOLKGEN(vkDestroySamplerYcbcrConversionKHR)
#endif /* defined(VK_KHR_sampler_ycbcr_conversion) */
#if defined(VK_KHR_shared_presentable_image)
VOLKGEN(vkGetSwapchainStatusKHR)
#endif /* defined(VK_KHR_shared_presentable_image) */
#if defined(VK_KHR_swapchain)
VOLKGEN(vkAcquireNextImageKHR)
VOLKGEN(vkCreateSwapchainKHR)
VOLKGEN(vkDestroySwapchainKHR)
VOLKGEN(vkGetSwapchainImagesKHR)
VOLKGEN(vkQueuePresentKHR)
#endif /* defined(VK_KHR_swapchain) */
#if defined(VK_NVX_device_generated_commands)
VOLKGEN(vkCmdProcessCommandsNVX)
VOLKGEN(vkCmdReserveSpaceForCommandsNVX)
VOLKGEN(vkCreateIndirectCommandsLayoutNVX)
VOLKGEN(vkCreateObjectTableNVX)
VOLKGEN(vkDestroyIndirectCommandsLayoutNVX)
VOLKGEN(vkDestroyObjectTableNVX)
VOLKGEN(vkRegisterObjectsNVX)
VOLKGEN(vkUnregisterObjectsNVX)
#endif /* defined(VK_NVX_device_generated_commands) */
#if defined(VK_NV_clip_space_w_scaling)
VOLKGEN(vkCmdSetViewportWScalingNV)
#endif /* defined(VK_NV_clip_space_w_scaling) */
#if defined(VK_NV_external_memory_win32)
VOLKGEN(vkGetMemoryWin32HandleNV)
#endif /* defined(VK_NV_external_memory_win32) */
#if (defined(VK_KHR_descriptor_update_template) && defined(VK_KHR_push_descriptor)) || (defined(VK_KHR_push_descriptor) && defined(VK_VERSION_1_1))
VOLKGEN(vkCmdPushDescriptorSetWithTemplateKHR)
#endif /* (defined(VK_KHR_descriptor_update_template) && defined(VK_KHR_push_descriptor)) || (defined(VK_KHR_push_descriptor) && defined(VK_VERSION_1_1)) */
#if (defined(VK_KHR_device_group) && defined(VK_KHR_surface)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1))
VOLKGEN(vkGetDeviceGroupPresentCapabilitiesKHR)
VOLKGEN(vkGetDeviceGroupSurfacePresentModesKHR)
#endif /* (defined(VK_KHR_device_group) && defined(VK_KHR_surface)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1)) */
#if (defined(VK_KHR_device_group) && defined(VK_KHR_swapchain)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1))
VOLKGEN(vkAcquireNextImage2KHR)
#endif /* (defined(VK_KHR_device_group) && defined(VK_KHR_swapchain)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1)) */
