/* This file is part of volk library and is automatically generated; do not modify it */
#if defined(VK_VERSION_1_0)
VOLKGEN(vkAllocateCommandBuffers, VkResult, (VkDevice device, const VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers))
VOLKGEN(vkAllocateDescriptorSets, VkResult, (VkDevice device, const VkDescriptorSetAllocateInfo* pAllocateInfo, VkDescriptorSet* pDescriptorSets))
VOLKGEN(vkAllocateMemory, VkResult, (VkDevice device, const VkMemoryAllocateInfo* pAllocateInfo, const VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory))
VOLKGEN(vkBeginCommandBuffer, VkResult, (VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo* pBeginInfo))
VOLKGEN(vkBindBufferMemory, VkResult, (VkDevice device, VkBuffer buffer, VkDeviceMemory memory, VkDeviceSize memoryOffset))
VOLKGEN(vkBindImageMemory, VkResult, (VkDevice device, VkImage image, VkDeviceMemory memory, VkDeviceSize memoryOffset))
VOLKGEN(vkCmdBeginQuery, void, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query, VkQueryControlFlags flags))
VOLKGEN(vkCmdBeginRenderPass, void, (VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents))
VOLKGEN(vkCmdBindDescriptorSets, void, (VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, uint32_t firstSet, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets, uint32_t dynamicOffsetCount, const uint32_t* pDynamicOffsets))
VOLKGEN(vkCmdBindIndexBuffer, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkIndexType indexType))
VOLKGEN(vkCmdBindPipeline, void, (VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline))
VOLKGEN(vkCmdBindVertexBuffers, void, (VkCommandBuffer commandBuffer, uint32_t firstBinding, uint32_t bindingCount, const VkBuffer* pBuffers, const VkDeviceSize* pOffsets))
VOLKGEN(vkCmdBlitImage, void, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageBlit* pRegions, VkFilter filter))
VOLKGEN(vkCmdClearAttachments, void, (VkCommandBuffer commandBuffer, uint32_t attachmentCount, const VkClearAttachment* pAttachments, uint32_t rectCount, const VkClearRect* pRects))
VOLKGEN(vkCmdClearColorImage, void, (VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, const VkClearColorValue* pColor, uint32_t rangeCount, const VkImageSubresourceRange* pRanges))
VOLKGEN(vkCmdClearDepthStencilImage, void, (VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, const VkClearDepthStencilValue* pDepthStencil, uint32_t rangeCount, const VkImageSubresourceRange* pRanges))
VOLKGEN(vkCmdCopyBuffer, void, (VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferCopy* pRegions))
VOLKGEN(vkCmdCopyBufferToImage, void, (VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkBufferImageCopy* pRegions))
VOLKGEN(vkCmdCopyImage, void, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageCopy* pRegions))
VOLKGEN(vkCmdCopyImageToBuffer, void, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferImageCopy* pRegions))
VOLKGEN(vkCmdCopyQueryPoolResults, void, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize stride, VkQueryResultFlags flags))
VOLKGEN(vkCmdDispatch, void, (VkCommandBuffer commandBuffer, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ))
VOLKGEN(vkCmdDispatchIndirect, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset))
VOLKGEN(vkCmdDraw, void, (VkCommandBuffer commandBuffer, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance))
VOLKGEN(vkCmdDrawIndexed, void, (VkCommandBuffer commandBuffer, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance))
VOLKGEN(vkCmdDrawIndexedIndirect, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, uint32_t drawCount, uint32_t stride))
VOLKGEN(vkCmdDrawIndirect, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, uint32_t drawCount, uint32_t stride))
VOLKGEN(vkCmdEndQuery, void, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query))
VOLKGEN(vkCmdEndRenderPass, void, (VkCommandBuffer commandBuffer))
VOLKGEN(vkCmdExecuteCommands, void, (VkCommandBuffer commandBuffer, uint32_t commandBufferCount, const VkCommandBuffer* pCommandBuffers))
VOLKGEN(vkCmdFillBuffer, void, (VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize size, uint32_t data))
VOLKGEN(vkCmdNextSubpass, void, (VkCommandBuffer commandBuffer, VkSubpassContents contents))
VOLKGEN(vkCmdPipelineBarrier, void, (VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkDependencyFlags dependencyFlags, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers))
VOLKGEN(vkCmdPushConstants, void, (VkCommandBuffer commandBuffer, VkPipelineLayout layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, const void* pValues))
VOLKGEN(vkCmdResetEvent, void, (VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask))
VOLKGEN(vkCmdResetQueryPool, void, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount))
VOLKGEN(vkCmdResolveImage, void, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageResolve* pRegions))
VOLKGEN(vkCmdSetBlendConstants, void, (VkCommandBuffer commandBuffer, const float blendConstants[4]))
VOLKGEN(vkCmdSetDepthBias, void, (VkCommandBuffer commandBuffer, float depthBiasConstantFactor, float depthBiasClamp, float depthBiasSlopeFactor))
VOLKGEN(vkCmdSetDepthBounds, void, (VkCommandBuffer commandBuffer, float minDepthBounds, float maxDepthBounds))
VOLKGEN(vkCmdSetEvent, void, (VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags stageMask))
VOLKGEN(vkCmdSetLineWidth, void, (VkCommandBuffer commandBuffer, float lineWidth))
VOLKGEN(vkCmdSetScissor, void, (VkCommandBuffer commandBuffer, uint32_t firstScissor, uint32_t scissorCount, const VkRect2D* pScissors))
VOLKGEN(vkCmdSetStencilCompareMask, void, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t compareMask))
VOLKGEN(vkCmdSetStencilReference, void, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t reference))
VOLKGEN(vkCmdSetStencilWriteMask, void, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t writeMask))
VOLKGEN(vkCmdSetViewport, void, (VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewport* pViewports))
VOLKGEN(vkCmdUpdateBuffer, void, (VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize dataSize, const void* pData))
VOLKGEN(vkCmdWaitEvents, void, (VkCommandBuffer commandBuffer, uint32_t eventCount, const VkEvent* pEvents, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers))
VOLKGEN(vkCmdWriteTimestamp, void, (VkCommandBuffer commandBuffer, VkPipelineStageFlagBits pipelineStage, VkQueryPool queryPool, uint32_t query))
VOLKGEN(vkCreateBuffer, VkResult, (VkDevice device, const VkBufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer))
VOLKGEN(vkCreateBufferView, VkResult, (VkDevice device, const VkBufferViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBufferView* pView))
VOLKGEN(vkCreateCommandPool, VkResult, (VkDevice device, const VkCommandPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkCommandPool* pCommandPool))
VOLKGEN(vkCreateComputePipelines, VkResult, (VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkComputePipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines))
VOLKGEN(vkCreateDescriptorPool, VkResult, (VkDevice device, const VkDescriptorPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool))
VOLKGEN(vkCreateDescriptorSetLayout, VkResult, (VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout))
VOLKGEN(vkCreateEvent, VkResult, (VkDevice device, const VkEventCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkEvent* pEvent))
VOLKGEN(vkCreateFence, VkResult, (VkDevice device, const VkFenceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence))
VOLKGEN(vkCreateFramebuffer, VkResult, (VkDevice device, const VkFramebufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer))
VOLKGEN(vkCreateGraphicsPipelines, VkResult, (VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkGraphicsPipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines))
VOLKGEN(vkCreateImage, VkResult, (VkDevice device, const VkImageCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImage* pImage))
VOLKGEN(vkCreateImageView, VkResult, (VkDevice device, const VkImageViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImageView* pView))
VOLKGEN(vkCreatePipelineCache, VkResult, (VkDevice device, const VkPipelineCacheCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineCache* pPipelineCache))
VOLKGEN(vkCreatePipelineLayout, VkResult, (VkDevice device, const VkPipelineLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout))
VOLKGEN(vkCreateQueryPool, VkResult, (VkDevice device, const VkQueryPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkQueryPool* pQueryPool))
VOLKGEN(vkCreateRenderPass, VkResult, (VkDevice device, const VkRenderPassCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass))
VOLKGEN(vkCreateSampler, VkResult, (VkDevice device, const VkSamplerCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSampler* pSampler))
VOLKGEN(vkCreateSemaphore, VkResult, (VkDevice device, const VkSemaphoreCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore))
VOLKGEN(vkCreateShaderModule, VkResult, (VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule))
VOLKGEN(vkDestroyBuffer, void, (VkDevice device, VkBuffer buffer, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyBufferView, void, (VkDevice device, VkBufferView bufferView, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyCommandPool, void, (VkDevice device, VkCommandPool commandPool, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyDescriptorPool, void, (VkDevice device, VkDescriptorPool descriptorPool, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyDescriptorSetLayout, void, (VkDevice device, VkDescriptorSetLayout descriptorSetLayout, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyDevice, void, (VkDevice device, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyEvent, void, (VkDevice device, VkEvent event, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyFence, void, (VkDevice device, VkFence fence, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyFramebuffer, void, (VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyImage, void, (VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyImageView, void, (VkDevice device, VkImageView imageView, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyPipeline, void, (VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyPipelineCache, void, (VkDevice device, VkPipelineCache pipelineCache, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyPipelineLayout, void, (VkDevice device, VkPipelineLayout pipelineLayout, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyQueryPool, void, (VkDevice device, VkQueryPool queryPool, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyRenderPass, void, (VkDevice device, VkRenderPass renderPass, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroySampler, void, (VkDevice device, VkSampler sampler, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroySemaphore, void, (VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyShaderModule, void, (VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDeviceWaitIdle, VkResult, (VkDevice device))
VOLKGEN(vkEndCommandBuffer, VkResult, (VkCommandBuffer commandBuffer))
VOLKGEN(vkFlushMappedMemoryRanges, VkResult, (VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges))
VOLKGEN(vkFreeCommandBuffers, void, (VkDevice device, VkCommandPool commandPool, uint32_t commandBufferCount, const VkCommandBuffer* pCommandBuffers))
VOLKGEN(vkFreeDescriptorSets, VkResult, (VkDevice device, VkDescriptorPool descriptorPool, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets))
VOLKGEN(vkFreeMemory, void, (VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkGetBufferMemoryRequirements, void, (VkDevice device, VkBuffer buffer, VkMemoryRequirements* pMemoryRequirements))
VOLKGEN(vkGetDeviceMemoryCommitment, void, (VkDevice device, VkDeviceMemory memory, VkDeviceSize* pCommittedMemoryInBytes))
VOLKGEN(vkGetDeviceQueue, void, (VkDevice device, uint32_t queueFamilyIndex, uint32_t queueIndex, VkQueue* pQueue))
VOLKGEN(vkGetEventStatus, VkResult, (VkDevice device, VkEvent event))
VOLKGEN(vkGetFenceStatus, VkResult, (VkDevice device, VkFence fence))
VOLKGEN(vkGetImageMemoryRequirements, void, (VkDevice device, VkImage image, VkMemoryRequirements* pMemoryRequirements))
VOLKGEN(vkGetImageSparseMemoryRequirements, void, (VkDevice device, VkImage image, uint32_t* pSparseMemoryRequirementCount, VkSparseImageMemoryRequirements* pSparseMemoryRequirements))
VOLKGEN(vkGetImageSubresourceLayout, void, (VkDevice device, VkImage image, const VkImageSubresource* pSubresource, VkSubresourceLayout* pLayout))
VOLKGEN(vkGetPipelineCacheData, VkResult, (VkDevice device, VkPipelineCache pipelineCache, size_t* pDataSize, void* pData))
VOLKGEN(vkGetQueryPoolResults, VkResult, (VkDevice device, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount, size_t dataSize, void* pData, VkDeviceSize stride, VkQueryResultFlags flags))
VOLKGEN(vkGetRenderAreaGranularity, void, (VkDevice device, VkRenderPass renderPass, VkExtent2D* pGranularity))
VOLKGEN(vkInvalidateMappedMemoryRanges, VkResult, (VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges))
VOLKGEN(vkMapMemory, VkResult, (VkDevice device, VkDeviceMemory memory, VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags, void** ppData))
VOLKGEN(vkMergePipelineCaches, VkResult, (VkDevice device, VkPipelineCache dstCache, uint32_t srcCacheCount, const VkPipelineCache* pSrcCaches))
VOLKGEN(vkQueueBindSparse, VkResult, (VkQueue queue, uint32_t bindInfoCount, const VkBindSparseInfo* pBindInfo, VkFence fence))
VOLKGEN(vkQueueSubmit, VkResult, (VkQueue queue, uint32_t submitCount, const VkSubmitInfo* pSubmits, VkFence fence))
VOLKGEN(vkQueueWaitIdle, VkResult, (VkQueue queue))
VOLKGEN(vkResetCommandBuffer, VkResult, (VkCommandBuffer commandBuffer, VkCommandBufferResetFlags flags))
VOLKGEN(vkResetCommandPool, VkResult, (VkDevice device, VkCommandPool commandPool, VkCommandPoolResetFlags flags))
VOLKGEN(vkResetDescriptorPool, VkResult, (VkDevice device, VkDescriptorPool descriptorPool, VkDescriptorPoolResetFlags flags))
VOLKGEN(vkResetEvent, VkResult, (VkDevice device, VkEvent event))
VOLKGEN(vkResetFences, VkResult, (VkDevice device, uint32_t fenceCount, const VkFence* pFences))
VOLKGEN(vkSetEvent, VkResult, (VkDevice device, VkEvent event))
VOLKGEN(vkUnmapMemory, void, (VkDevice device, VkDeviceMemory memory))
VOLKGEN(vkUpdateDescriptorSets, void, (VkDevice device, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites, uint32_t descriptorCopyCount, const VkCopyDescriptorSet* pDescriptorCopies))
VOLKGEN(vkWaitForFences, VkResult, (VkDevice device, uint32_t fenceCount, const VkFence* pFences, VkBool32 waitAll, uint64_t timeout))
#endif /* defined(VK_VERSION_1_0) */
#if defined(VK_VERSION_1_1)
VOLKGEN(vkBindBufferMemory2, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindBufferMemoryInfo* pBindInfos))
VOLKGEN(vkBindImageMemory2, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindImageMemoryInfo* pBindInfos))
VOLKGEN(vkCmdDispatchBase, void, (VkCommandBuffer commandBuffer, uint32_t baseGroupX, uint32_t baseGroupY, uint32_t baseGroupZ, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ))
VOLKGEN(vkCmdSetDeviceMask, void, (VkCommandBuffer commandBuffer, uint32_t deviceMask))
VOLKGEN(vkCreateDescriptorUpdateTemplate, VkResult, (VkDevice device, const VkDescriptorUpdateTemplateCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorUpdateTemplate* pDescriptorUpdateTemplate))
VOLKGEN(vkCreateSamplerYcbcrConversion, VkResult, (VkDevice device, const VkSamplerYcbcrConversionCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSamplerYcbcrConversion* pYcbcrConversion))
VOLKGEN(vkDestroyDescriptorUpdateTemplate, void, (VkDevice device, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroySamplerYcbcrConversion, void, (VkDevice device, VkSamplerYcbcrConversion ycbcrConversion, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkGetBufferMemoryRequirements2, void, (VkDevice device, const VkBufferMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements))
VOLKGEN(vkGetDescriptorSetLayoutSupport, void, (VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, VkDescriptorSetLayoutSupport* pSupport))
VOLKGEN(vkGetDeviceGroupPeerMemoryFeatures, void, (VkDevice device, uint32_t heapIndex, uint32_t localDeviceIndex, uint32_t remoteDeviceIndex, VkPeerMemoryFeatureFlags* pPeerMemoryFeatures))
VOLKGEN(vkGetDeviceQueue2, void, (VkDevice device, const VkDeviceQueueInfo2* pQueueInfo, VkQueue* pQueue))
VOLKGEN(vkGetImageMemoryRequirements2, void, (VkDevice device, const VkImageMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements))
VOLKGEN(vkGetImageSparseMemoryRequirements2, void, (VkDevice device, const VkImageSparseMemoryRequirementsInfo2* pInfo, uint32_t* pSparseMemoryRequirementCount, VkSparseImageMemoryRequirements2* pSparseMemoryRequirements))
VOLKGEN(vkTrimCommandPool, void, (VkDevice device, VkCommandPool commandPool, VkCommandPoolTrimFlags flags))
VOLKGEN(vkUpdateDescriptorSetWithTemplate, void, (VkDevice device, VkDescriptorSet descriptorSet, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const void* pData))
#endif /* defined(VK_VERSION_1_1) */
#if defined(VK_AMD_buffer_marker)
VOLKGEN(vkCmdWriteBufferMarkerAMD, void, (VkCommandBuffer commandBuffer, VkPipelineStageFlagBits pipelineStage, VkBuffer dstBuffer, VkDeviceSize dstOffset, uint32_t marker))
#endif /* defined(VK_AMD_buffer_marker) */
#if defined(VK_AMD_draw_indirect_count)
VOLKGEN(vkCmdDrawIndexedIndirectCountAMD, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkBuffer countBuffer, VkDeviceSize countBufferOffset, uint32_t maxDrawCount, uint32_t stride))
VOLKGEN(vkCmdDrawIndirectCountAMD, void, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkBuffer countBuffer, VkDeviceSize countBufferOffset, uint32_t maxDrawCount, uint32_t stride))
#endif /* defined(VK_AMD_draw_indirect_count) */
#if defined(VK_AMD_shader_info)
VOLKGEN(vkGetShaderInfoAMD, VkResult, (VkDevice device, VkPipeline pipeline, VkShaderStageFlagBits shaderStage, VkShaderInfoTypeAMD infoType, size_t* pInfoSize, void* pInfo))
#endif /* defined(VK_AMD_shader_info) */
#if defined(VK_ANDROID_external_memory_android_hardware_buffer)
VOLKGEN(vkGetAndroidHardwareBufferPropertiesANDROID, VkResult, (VkDevice device, const struct AHardwareBuffer* buffer, VkAndroidHardwareBufferPropertiesANDROID* pProperties))
VOLKGEN(vkGetMemoryAndroidHardwareBufferANDROID, VkResult, (VkDevice device, const VkMemoryGetAndroidHardwareBufferInfoANDROID* pInfo, struct AHardwareBuffer** pBuffer))
#endif /* defined(VK_ANDROID_external_memory_android_hardware_buffer) */
#if defined(VK_ANDROID_native_buffer)
VOLKGEN(vkAcquireImageANDROID, VkResult, (VkDevice device, VkImage image, int nativeFenceFd, VkSemaphore semaphore, VkFence fence))
VOLKGEN(vkGetSwapchainGrallocUsageANDROID, VkResult, (VkDevice device, VkFormat format, VkImageUsageFlags imageUsage, int* grallocUsage))
VOLKGEN(vkQueueSignalReleaseImageANDROID, VkResult, (VkQueue queue, uint32_t waitSemaphoreCount, const VkSemaphore* pWaitSemaphores, VkImage image, int* pNativeFenceFd))
#endif /* defined(VK_ANDROID_native_buffer) */
#if defined(VK_EXT_debug_marker)
VOLKGEN(vkCmdDebugMarkerBeginEXT, void, (VkCommandBuffer commandBuffer, const VkDebugMarkerMarkerInfoEXT* pMarkerInfo))
VOLKGEN(vkCmdDebugMarkerEndEXT, void, (VkCommandBuffer commandBuffer))
VOLKGEN(vkCmdDebugMarkerInsertEXT, void, (VkCommandBuffer commandBuffer, const VkDebugMarkerMarkerInfoEXT* pMarkerInfo))
VOLKGEN(vkDebugMarkerSetObjectNameEXT, VkResult, (VkDevice device, const VkDebugMarkerObjectNameInfoEXT* pNameInfo))
VOLKGEN(vkDebugMarkerSetObjectTagEXT, VkResult, (VkDevice device, const VkDebugMarkerObjectTagInfoEXT* pTagInfo))
#endif /* defined(VK_EXT_debug_marker) */
#if defined(VK_EXT_debug_utils)
VOLKGEN(vkCmdBeginDebugUtilsLabelEXT, void, (VkCommandBuffer commandBuffer, const VkDebugUtilsLabelEXT* pLabelInfo))
VOLKGEN(vkCmdEndDebugUtilsLabelEXT, void, (VkCommandBuffer commandBuffer))
VOLKGEN(vkCmdInsertDebugUtilsLabelEXT, void, (VkCommandBuffer commandBuffer, const VkDebugUtilsLabelEXT* pLabelInfo))
VOLKGEN(vkQueueBeginDebugUtilsLabelEXT, void, (VkQueue queue, const VkDebugUtilsLabelEXT* pLabelInfo))
VOLKGEN(vkQueueEndDebugUtilsLabelEXT, void, (VkQueue queue))
VOLKGEN(vkQueueInsertDebugUtilsLabelEXT, void, (VkQueue queue, const VkDebugUtilsLabelEXT* pLabelInfo))
VOLKGEN(vkSetDebugUtilsObjectNameEXT, VkResult, (VkDevice device, const VkDebugUtilsObjectNameInfoEXT* pNameInfo))
VOLKGEN(vkSetDebugUtilsObjectTagEXT, VkResult, (VkDevice device, const VkDebugUtilsObjectTagInfoEXT* pTagInfo))
#endif /* defined(VK_EXT_debug_utils) */
#if defined(VK_EXT_discard_rectangles)
VOLKGEN(vkCmdSetDiscardRectangleEXT, void, (VkCommandBuffer commandBuffer, uint32_t firstDiscardRectangle, uint32_t discardRectangleCount, const VkRect2D* pDiscardRectangles))
#endif /* defined(VK_EXT_discard_rectangles) */
#if defined(VK_EXT_display_control)
VOLKGEN(vkDisplayPowerControlEXT, VkResult, (VkDevice device, VkDisplayKHR display, const VkDisplayPowerInfoEXT* pDisplayPowerInfo))
VOLKGEN(vkGetSwapchainCounterEXT, VkResult, (VkDevice device, VkSwapchainKHR swapchain, VkSurfaceCounterFlagBitsEXT counter, uint64_t* pCounterValue))
VOLKGEN(vkRegisterDeviceEventEXT, VkResult, (VkDevice device, const VkDeviceEventInfoEXT* pDeviceEventInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence))
VOLKGEN(vkRegisterDisplayEventEXT, VkResult, (VkDevice device, VkDisplayKHR display, const VkDisplayEventInfoEXT* pDisplayEventInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence))
#endif /* defined(VK_EXT_display_control) */
#if defined(VK_EXT_external_memory_host)
VOLKGEN(vkGetMemoryHostPointerPropertiesEXT, VkResult, (VkDevice device, VkExternalMemoryHandleTypeFlagBits handleType, const void* pHostPointer, VkMemoryHostPointerPropertiesEXT* pMemoryHostPointerProperties))
#endif /* defined(VK_EXT_external_memory_host) */
#if defined(VK_EXT_hdr_metadata)
VOLKGEN(vkSetHdrMetadataEXT, void, (VkDevice device, uint32_t swapchainCount, const VkSwapchainKHR* pSwapchains, const VkHdrMetadataEXT* pMetadata))
#endif /* defined(VK_EXT_hdr_metadata) */
#if defined(VK_EXT_sample_locations)
VOLKGEN(vkCmdSetSampleLocationsEXT, void, (VkCommandBuffer commandBuffer, const VkSampleLocationsInfoEXT* pSampleLocationsInfo))
#endif /* defined(VK_EXT_sample_locations) */
#if defined(VK_EXT_validation_cache)
VOLKGEN(vkCreateValidationCacheEXT, VkResult, (VkDevice device, const VkValidationCacheCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkValidationCacheEXT* pValidationCache))
VOLKGEN(vkDestroyValidationCacheEXT, void, (VkDevice device, VkValidationCacheEXT validationCache, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkGetValidationCacheDataEXT, VkResult, (VkDevice device, VkValidationCacheEXT validationCache, size_t* pDataSize, void* pData))
VOLKGEN(vkMergeValidationCachesEXT, VkResult, (VkDevice device, VkValidationCacheEXT dstCache, uint32_t srcCacheCount, const VkValidationCacheEXT* pSrcCaches))
#endif /* defined(VK_EXT_validation_cache) */
#if defined(VK_GOOGLE_display_timing)
VOLKGEN(vkGetPastPresentationTimingGOOGLE, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint32_t* pPresentationTimingCount, VkPastPresentationTimingGOOGLE* pPresentationTimings))
VOLKGEN(vkGetRefreshCycleDurationGOOGLE, VkResult, (VkDevice device, VkSwapchainKHR swapchain, VkRefreshCycleDurationGOOGLE* pDisplayTimingProperties))
#endif /* defined(VK_GOOGLE_display_timing) */
#if defined(VK_KHR_bind_memory2)
VOLKGEN(vkBindBufferMemory2KHR, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindBufferMemoryInfo* pBindInfos))
VOLKGEN(vkBindImageMemory2KHR, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindImageMemoryInfo* pBindInfos))
#endif /* defined(VK_KHR_bind_memory2) */
#if defined(VK_KHR_descriptor_update_template)
VOLKGEN(vkCreateDescriptorUpdateTemplateKHR, VkResult, (VkDevice device, const VkDescriptorUpdateTemplateCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorUpdateTemplate* pDescriptorUpdateTemplate))
VOLKGEN(vkDestroyDescriptorUpdateTemplateKHR, void, (VkDevice device, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkUpdateDescriptorSetWithTemplateKHR, void, (VkDevice device, VkDescriptorSet descriptorSet, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const void* pData))
#endif /* defined(VK_KHR_descriptor_update_template) */
#if defined(VK_KHR_device_group)
VOLKGEN(vkCmdDispatchBaseKHR, void, (VkCommandBuffer commandBuffer, uint32_t baseGroupX, uint32_t baseGroupY, uint32_t baseGroupZ, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ))
VOLKGEN(vkCmdSetDeviceMaskKHR, void, (VkCommandBuffer commandBuffer, uint32_t deviceMask))
VOLKGEN(vkGetDeviceGroupPeerMemoryFeaturesKHR, void, (VkDevice device, uint32_t heapIndex, uint32_t localDeviceIndex, uint32_t remoteDeviceIndex, VkPeerMemoryFeatureFlags* pPeerMemoryFeatures))
#endif /* defined(VK_KHR_device_group) */
#if defined(VK_KHR_display_swapchain)
VOLKGEN(vkCreateSharedSwapchainsKHR, VkResult, (VkDevice device, uint32_t swapchainCount, const VkSwapchainCreateInfoKHR* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkSwapchainKHR* pSwapchains))
#endif /* defined(VK_KHR_display_swapchain) */
#if defined(VK_KHR_external_fence_fd)
VOLKGEN(vkGetFenceFdKHR, VkResult, (VkDevice device, const VkFenceGetFdInfoKHR* pGetFdInfo, int* pFd))
VOLKGEN(vkImportFenceFdKHR, VkResult, (VkDevice device, const VkImportFenceFdInfoKHR* pImportFenceFdInfo))
#endif /* defined(VK_KHR_external_fence_fd) */
#if defined(VK_KHR_external_fence_win32)
VOLKGEN(vkGetFenceWin32HandleKHR, VkResult, (VkDevice device, const VkFenceGetWin32HandleInfoKHR* pGetWin32HandleInfo, HANDLE* pHandle))
VOLKGEN(vkImportFenceWin32HandleKHR, VkResult, (VkDevice device, const VkImportFenceWin32HandleInfoKHR* pImportFenceWin32HandleInfo))
#endif /* defined(VK_KHR_external_fence_win32) */
#if defined(VK_KHR_external_memory_fd)
VOLKGEN(vkGetMemoryFdKHR, VkResult, (VkDevice device, const VkMemoryGetFdInfoKHR* pGetFdInfo, int* pFd))
VOLKGEN(vkGetMemoryFdPropertiesKHR, VkResult, (VkDevice device, VkExternalMemoryHandleTypeFlagBits handleType, int fd, VkMemoryFdPropertiesKHR* pMemoryFdProperties))
#endif /* defined(VK_KHR_external_memory_fd) */
#if defined(VK_KHR_external_memory_win32)
VOLKGEN(vkGetMemoryWin32HandleKHR, VkResult, (VkDevice device, const VkMemoryGetWin32HandleInfoKHR* pGetWin32HandleInfo, HANDLE* pHandle))
VOLKGEN(vkGetMemoryWin32HandlePropertiesKHR, VkResult, (VkDevice device, VkExternalMemoryHandleTypeFlagBits handleType, HANDLE handle, VkMemoryWin32HandlePropertiesKHR* pMemoryWin32HandleProperties))
#endif /* defined(VK_KHR_external_memory_win32) */
#if defined(VK_KHR_external_semaphore_fd)
VOLKGEN(vkGetSemaphoreFdKHR, VkResult, (VkDevice device, const VkSemaphoreGetFdInfoKHR* pGetFdInfo, int* pFd))
VOLKGEN(vkImportSemaphoreFdKHR, VkResult, (VkDevice device, const VkImportSemaphoreFdInfoKHR* pImportSemaphoreFdInfo))
#endif /* defined(VK_KHR_external_semaphore_fd) */
#if defined(VK_KHR_external_semaphore_win32)
VOLKGEN(vkGetSemaphoreWin32HandleKHR, VkResult, (VkDevice device, const VkSemaphoreGetWin32HandleInfoKHR* pGetWin32HandleInfo, HANDLE* pHandle))
VOLKGEN(vkImportSemaphoreWin32HandleKHR, VkResult, (VkDevice device, const VkImportSemaphoreWin32HandleInfoKHR* pImportSemaphoreWin32HandleInfo))
#endif /* defined(VK_KHR_external_semaphore_win32) */
#if defined(VK_KHR_get_memory_requirements2)
VOLKGEN(vkGetBufferMemoryRequirements2KHR, void, (VkDevice device, const VkBufferMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements))
VOLKGEN(vkGetImageMemoryRequirements2KHR, void, (VkDevice device, const VkImageMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements))
VOLKGEN(vkGetImageSparseMemoryRequirements2KHR, void, (VkDevice device, const VkImageSparseMemoryRequirementsInfo2* pInfo, uint32_t* pSparseMemoryRequirementCount, VkSparseImageMemoryRequirements2* pSparseMemoryRequirements))
#endif /* defined(VK_KHR_get_memory_requirements2) */
#if defined(VK_KHR_maintenance1)
VOLKGEN(vkTrimCommandPoolKHR, void, (VkDevice device, VkCommandPool commandPool, VkCommandPoolTrimFlags flags))
#endif /* defined(VK_KHR_maintenance1) */
#if defined(VK_KHR_maintenance3)
VOLKGEN(vkGetDescriptorSetLayoutSupportKHR, void, (VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, VkDescriptorSetLayoutSupport* pSupport))
#endif /* defined(VK_KHR_maintenance3) */
#if defined(VK_KHR_push_descriptor)
VOLKGEN(vkCmdPushDescriptorSetKHR, void, (VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, uint32_t set, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites))
#endif /* defined(VK_KHR_push_descriptor) */
#if defined(VK_KHR_sampler_ycbcr_conversion)
VOLKGEN(vkCreateSamplerYcbcrConversionKHR, VkResult, (VkDevice device, const VkSamplerYcbcrConversionCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSamplerYcbcrConversion* pYcbcrConversion))
VOLKGEN(vkDestroySamplerYcbcrConversionKHR, void, (VkDevice device, VkSamplerYcbcrConversion ycbcrConversion, const VkAllocationCallbacks* pAllocator))
#endif /* defined(VK_KHR_sampler_ycbcr_conversion) */
#if defined(VK_KHR_shared_presentable_image)
VOLKGEN(vkGetSwapchainStatusKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain))
#endif /* defined(VK_KHR_shared_presentable_image) */
#if defined(VK_KHR_swapchain)
VOLKGEN(vkAcquireNextImageKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint64_t timeout, VkSemaphore semaphore, VkFence fence, uint32_t* pImageIndex))
VOLKGEN(vkCreateSwapchainKHR, VkResult, (VkDevice device, const VkSwapchainCreateInfoKHR* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSwapchainKHR* pSwapchain))
VOLKGEN(vkDestroySwapchainKHR, void, (VkDevice device, VkSwapchainKHR swapchain, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkGetSwapchainImagesKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint32_t* pSwapchainImageCount, VkImage* pSwapchainImages))
VOLKGEN(vkQueuePresentKHR, VkResult, (VkQueue queue, const VkPresentInfoKHR* pPresentInfo))
#endif /* defined(VK_KHR_swapchain) */
#if defined(VK_NVX_device_generated_commands)
VOLKGEN(vkCmdProcessCommandsNVX, void, (VkCommandBuffer commandBuffer, const VkCmdProcessCommandsInfoNVX* pProcessCommandsInfo))
VOLKGEN(vkCmdReserveSpaceForCommandsNVX, void, (VkCommandBuffer commandBuffer, const VkCmdReserveSpaceForCommandsInfoNVX* pReserveSpaceInfo))
VOLKGEN(vkCreateIndirectCommandsLayoutNVX, VkResult, (VkDevice device, const VkIndirectCommandsLayoutCreateInfoNVX* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutNVX* pIndirectCommandsLayout))
VOLKGEN(vkCreateObjectTableNVX, VkResult, (VkDevice device, const VkObjectTableCreateInfoNVX* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkObjectTableNVX* pObjectTable))
VOLKGEN(vkDestroyIndirectCommandsLayoutNVX, void, (VkDevice device, VkIndirectCommandsLayoutNVX indirectCommandsLayout, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkDestroyObjectTableNVX, void, (VkDevice device, VkObjectTableNVX objectTable, const VkAllocationCallbacks* pAllocator))
VOLKGEN(vkRegisterObjectsNVX, VkResult, (VkDevice device, VkObjectTableNVX objectTable, uint32_t objectCount, const VkObjectTableEntryNVX* const*    ppObjectTableEntries, const uint32_t* pObjectIndices))
VOLKGEN(vkUnregisterObjectsNVX, VkResult, (VkDevice device, VkObjectTableNVX objectTable, uint32_t objectCount, const VkObjectEntryTypeNVX* pObjectEntryTypes, const uint32_t* pObjectIndices))
#endif /* defined(VK_NVX_device_generated_commands) */
#if defined(VK_NV_clip_space_w_scaling)
VOLKGEN(vkCmdSetViewportWScalingNV, void, (VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewportWScalingNV* pViewportWScalings))
#endif /* defined(VK_NV_clip_space_w_scaling) */
#if defined(VK_NV_external_memory_win32)
VOLKGEN(vkGetMemoryWin32HandleNV, VkResult, (VkDevice device, VkDeviceMemory memory, VkExternalMemoryHandleTypeFlagsNV handleType, HANDLE* pHandle))
#endif /* defined(VK_NV_external_memory_win32) */
#if (defined(VK_KHR_descriptor_update_template) && defined(VK_KHR_push_descriptor)) || (defined(VK_KHR_push_descriptor) && defined(VK_VERSION_1_1))
VOLKGEN(vkCmdPushDescriptorSetWithTemplateKHR, void, (VkCommandBuffer commandBuffer, VkDescriptorUpdateTemplate descriptorUpdateTemplate, VkPipelineLayout layout, uint32_t set, const void* pData))
#endif /* (defined(VK_KHR_descriptor_update_template) && defined(VK_KHR_push_descriptor)) || (defined(VK_KHR_push_descriptor) && defined(VK_VERSION_1_1)) */
#if (defined(VK_KHR_device_group) && defined(VK_KHR_surface)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1))
VOLKGEN(vkGetDeviceGroupPresentCapabilitiesKHR, VkResult, (VkDevice device, VkDeviceGroupPresentCapabilitiesKHR* pDeviceGroupPresentCapabilities))
VOLKGEN(vkGetDeviceGroupSurfacePresentModesKHR, VkResult, (VkDevice device, VkSurfaceKHR surface, VkDeviceGroupPresentModeFlagsKHR* pModes))
#endif /* (defined(VK_KHR_device_group) && defined(VK_KHR_surface)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1)) */
#if (defined(VK_KHR_device_group) && defined(VK_KHR_swapchain)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1))
VOLKGEN(vkAcquireNextImage2KHR, VkResult, (VkDevice device, const VkAcquireNextImageInfoKHR* pAcquireInfo, uint32_t* pImageIndex))
#endif /* (defined(VK_KHR_device_group) && defined(VK_KHR_swapchain)) || (defined(VK_KHR_swapchain) && defined(VK_VERSION_1_1)) */
